name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  linter:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Headers
        run: ${GITHUB_WORKSPACE}/check_header_validity.sh

      - name: Linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          extensions: 'c,h'
          extra-args: '-I include -I submodules/vector/include'

  build:
    needs: linter
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2019, macos-11.0]
        include:
          - os: ubuntu-22.04
            compiler: gcc
          - os: ubuntu-22.04
            compiler: clang
          - os: windows-2019
            compiler: msvc
          - os: macos-11.0
            compiler: clang
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          cmake -B build
          cmake --build build

  tests-linux:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update submodules
        run: |
          git submodule update --init --recursive

      - name: Build submodules
        run: |
          sudo apt-get install -y meson gcovr
          ./build_submodules.sh TESTING

      - name: Run tests
        run: |
          ./run_tests.sh

      - name: Coverage report
        run: |
          mkdir -p coverage
          gcovr -e tests --html-details coverage/index.html
          gcovr -e tests --xml coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: Coverage-report
          path: ./coverage

      - name: Upload ECS code coverage
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./coverage
          target-folder: docs/coverage
          branch: gh-pages

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
