name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y && sudo apt-get upgrade

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          cmake -B build
          cmake --build build

  tests-linux:
    runs-on: ubuntu-22.04
    needs: build-linux
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y && sudo apt-get upgrade

      - name: Install criterion
        run: |
          sudo apt-get install gcovr
          sudo apt-get install meson
          git clone --recursive https://github.com/Snaipe/Criterion Criterion
          cd Criterion
          meson build
          ninja -C build
          sudo ninja -C build install

      - name: Make Criterion available
        run: |
          cd Criterion
          sudo ldconfig

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          cmake -B build -DTESTING=ON
          cmake --build build
          cd build
          ctest --output-on-failure
          cd ..

      - name: Coverage report
        run: |
          mkdir -p coverage
          gcovr -e tests --html-details coverage/index.html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: Coverage-report
          path: ./coverage

      - name: Upload ECS code coverage
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./coverage
          target-folder: docs/coverage
          branch: gh-pages